### ISSUE TITLE
[MetaData] a PUT call in an nonexisting data result in a 500 HTTP Code error

### ISSUE THREAD

**Issue by arcadmlafon** [ARCAD-Software/AFS#69]
Calling a PUT /data/{type}/{id} on a non existing data (type or id) should return a 404 HTTP error code, but it return a 500 error code with the following stack trace on the server side:

```
SEVERE: Exception or error caught in server resource
java.lang.NullPointerException
    at com.arcadsoftware.metadata.rest.internal.MetaDataItemResource.put(MetaDataItemResource.java:554)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:595)
    at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)

```

**Comment by arcadmlafon** [comment]
fixed by commit 3823957f86a5ae07f9291b050f22074a1527e92c
